/* Description Game questions — loaded separately */
(function () {
  window.CAA = window.CAA || {};
  window.CAA.content = window.CAA.content || {};

  window.CAA.content.descriptionGame = [
    // ANIMALS
    { answer: "Chameleon", description: "This reptile is famous for changing the colour of its skin to blend into its surroundings. It has a very long sticky tongue to catch insects and eyes that can move independently of each other.", options: ["Gecko", "Chameleon", "Iguana", "Salamander"], topic: "Animals", emoji: "🦎", difficulty: "medium" },
    { answer: "Platypus", description: "This extraordinary Australian mammal has a duck-like bill, webbed feet, and lays eggs instead of giving birth. The male also has a venomous spur on its hind leg.", options: ["Echidna", "Wombat", "Platypus", "Quokka"], topic: "Animals", emoji: "🦆", difficulty: "hard" },
    { answer: "Octopus", description: "This ocean creature has eight arms covered in suckers, three hearts, blue blood, and can squirt ink to escape predators. It is considered the most intelligent invertebrate.", options: ["Squid", "Jellyfish", "Octopus", "Cuttlefish"], topic: "Animals", emoji: "🐙", difficulty: "medium" },
    { answer: "Flamingo", description: "This tall wading bird gets its distinctive pink colour from the pigments in the algae and shrimps it eats. It often stands on one leg and lives in large flocks near salty lakes.", options: ["Pelican", "Ibis", "Flamingo", "Heron"], topic: "Animals", emoji: "🦩", difficulty: "easy" },
    { answer: "Narwhal", description: "Called the unicorn of the sea, this Arctic whale is known for its long spiral ivory tusk, which is actually an enlarged tooth that can reach up to three metres in length.", options: ["Beluga", "Narwhal", "Orca", "Dugong"], topic: "Animals", emoji: "🌊", difficulty: "hard" },
    { answer: "Axolotl", description: "This remarkable Mexican salamander keeps its larval features its whole life, a process called neoteny. It can regrow entire limbs, its heart, and even parts of its brain.", options: ["Mudpuppy", "Axolotl", "Newt", "Caecilian"], topic: "Animals", emoji: "🦈", difficulty: "hard" },
    // SCIENCE
    { answer: "Photosynthesis", description: "This biological process converts sunlight, water, and carbon dioxide into glucose and oxygen. Without it, there would be no oxygen on Earth and no food for most living creatures.", options: ["Respiration", "Photosynthesis", "Fermentation", "Osmosis"], topic: "Science", emoji: "🌿", difficulty: "medium" },
    { answer: "Black hole", description: "This astronomical phenomenon is a region where gravity is so extreme that not even light can escape. It forms when a massive star collapses under its own gravity at the end of its life.", options: ["Neutron star", "Quasar", "Black hole", "Pulsar"], topic: "Science", emoji: "🌌", difficulty: "medium" },
    { answer: "DNA", description: "This molecule shaped like a double helix carries the genetic instructions for all living organisms. It was discovered in 1953 by Watson, Crick, Franklin, and Wilkins.", options: ["RNA", "Protein", "Chromosome", "DNA"], topic: "Science", emoji: "🧬", difficulty: "easy" },
    { answer: "Supernova", description: "This colossal stellar explosion occurs at the end of a massive star's life. For a brief period it can outshine an entire galaxy, scattering heavy elements like iron and gold across space.", options: ["Nova", "Nebula", "Supernova", "Solar flare"], topic: "Science", emoji: "💥", difficulty: "hard" },
    { answer: "Mitosis", description: "This is the type of cell division in which one parent cell divides into two genetically identical daughter cells. It is the mechanism responsible for growth and tissue repair in the body.", options: ["Meiosis", "Mitosis", "Fission", "Cloning"], topic: "Science", emoji: "🔬", difficulty: "hard" },
    { answer: "Earthquake", description: "This natural disaster occurs when two tectonic plates suddenly slip past one another, releasing energy as seismic waves that can level cities and trigger tsunamis.", options: ["Volcano", "Tsunami", "Earthquake", "Avalanche"], topic: "Science", emoji: "🌍", difficulty: "easy" },
    { answer: "Glacier", description: "This massive body of dense ice forms over thousands of years from compacted snow. It moves very slowly under its own weight and has shaped many of today's mountain valleys.", options: ["Iceberg", "Permafrost", "Glacier", "Tundra"], topic: "Science", emoji: "🏔️", difficulty: "medium" },
    { answer: "Superconductor", description: "This material, when cooled to extremely low temperatures, conducts electricity with zero resistance, meaning no energy is lost as heat. It is used in MRI machines and particle accelerators.", options: ["Semiconductor", "Superconductor", "Conductor", "Insulator"], topic: "Science", emoji: "⚡", difficulty: "hard" },
    // GEOGRAPHY
    { answer: "Amazon", description: "This is the world's largest river by water volume, flowing mainly through Brazil. Its surrounding rainforest produces about 20 percent of Earth's oxygen and shelters millions of species.", options: ["Nile", "Congo", "Amazon", "Yangtze"], topic: "Geography", emoji: "🌊", difficulty: "easy" },
    { answer: "Sahara", description: "This is the world's largest hot desert, covering roughly 9 million square kilometres in North Africa. Surprisingly, only about 25 percent of it is covered by sand dunes.", options: ["Gobi", "Atacama", "Sahara", "Arabian"], topic: "Geography", emoji: "🏜️", difficulty: "easy" },
    { answer: "Iceland", description: "This Nordic island sits on the Mid-Atlantic Ridge, making it one of Earth's most volcanically active places. Despite its name it is quite green, and nearly all its electricity comes from geothermal and hydropower.", options: ["Greenland", "Norway", "Finland", "Iceland"], topic: "Geography", emoji: "🌋", difficulty: "medium" },
    { answer: "Dead Sea", description: "This landlocked salt lake between Jordan and Israel is so dense with salt that people float effortlessly on its surface without trying. At 430 metres below sea level it is the lowest point on Earth.", options: ["Caspian Sea", "Dead Sea", "Red Sea", "Aral Sea"], topic: "Geography", emoji: "🏖️", difficulty: "medium" },
    { answer: "Patagonia", description: "This vast windswept region at the southern tip of South America is shared between Argentina and Chile. It contains glaciers, fjords, steppes, and some of the world's least-visited wilderness.", options: ["Pampas", "Patagonia", "Amazonia", "Mato Grosso"], topic: "Geography", emoji: "⛰️", difficulty: "hard" },
    { answer: "Archipelago", description: "This geographical term describes a chain or cluster of islands. Indonesia, the Philippines, and Greece are famous examples, each consisting of hundreds or thousands of individual islands.", options: ["Peninsula", "Isthmus", "Archipelago", "Atoll"], topic: "Geography", emoji: "🏝️", difficulty: "hard" },
    // SPORTS
    { answer: "Fencing", description: "This Olympic combat sport uses sword-like weapons. Two competitors try to score points by touching their opponent. The three weapons used are the foil, the epee, and the sabre.", options: ["Archery", "Wrestling", "Fencing", "Taekwondo"], topic: "Sports", emoji: "🤺", difficulty: "medium" },
    { answer: "Biathlon", description: "This demanding winter Olympic discipline combines cross-country skiing with rifle shooting. Athletes must ski kilometres then stop and shoot at targets accurately while their heart pounds rapidly.", options: ["Triathlon", "Decathlon", "Biathlon", "Pentathlon"], topic: "Sports", emoji: "⛷️", difficulty: "hard" },
    { answer: "Curling", description: "In this winter sport two teams of four take turns sliding heavy granite stones down a sheet of ice towards a target called the house. Teammates sweep the ice to guide the stone's path.", options: ["Bobsled", "Luge", "Curling", "Skeleton"], topic: "Sports", emoji: "🥌", difficulty: "medium" },
    { answer: "Polo", description: "This sport is played on horseback. Two teams of four riders use long-handled mallets to hit a small ball through the opposing team's goalposts. It is one of the world's oldest team sports.", options: ["Croquet", "Polo", "Lacrosse", "Hurling"], topic: "Sports", emoji: "🏇", difficulty: "medium" },
    { answer: "Sepak Takraw", description: "This Southeast Asian sport resembles volleyball but players can only use their feet, knees, chest, and head, never their hands. Players perform acrobatic bicycle-kick spikes over the net.", options: ["Footvolley", "Sepak Takraw", "Kabaddi", "Chinlone"], topic: "Sports", emoji: "⚽", difficulty: "hard" },
    // OBJECTS
    { answer: "Periscope", description: "This optical device uses two mirrors arranged at 45-degree angles so that someone can see objects not in their direct line of sight. It is famously used in submarines to observe the surface from underwater.", options: ["Telescope", "Microscope", "Periscope", "Kaleidoscope"], topic: "Objects", emoji: "🔭", difficulty: "medium" },
    { answer: "Abacus", description: "This ancient calculating device uses rows of beads on wires to perform arithmetic. Invented thousands of years ago in Asia, it is still used today by some traders and in mathematics education.", options: ["Calculator", "Abacus", "Slide rule", "Soroban"], topic: "Objects", emoji: "🧮", difficulty: "medium" },
    { answer: "Metronome", description: "This device produces a regular audible click to help musicians keep a steady tempo while practising. It can be a swinging mechanical pendulum or a compact digital device.", options: ["Tuning fork", "Metronome", "Synthesiser", "Amplifier"], topic: "Objects", emoji: "🎵", difficulty: "hard" },
    { answer: "Thermometer", description: "This instrument measures temperature based on the principle that liquids expand when heated. It was first developed in the 17th century and now exists in digital, glass, and infrared varieties.", options: ["Barometer", "Hygrometer", "Thermometer", "Altimeter"], topic: "Objects", emoji: "🌡️", difficulty: "easy" },
    { answer: "Compass", description: "This navigation tool contains a magnetised needle that always aligns with Earth's magnetic field, pointing towards magnetic north. Before GPS, every ship, army, and explorer depended on one.", options: ["Sextant", "Astrolabe", "Compass", "Barometer"], topic: "Objects", emoji: "🧭", difficulty: "easy" },
    // HISTORY
    { answer: "Hieroglyphics", description: "This writing system used by the ancient Egyptians consists of pictorial symbols. Their meaning was lost for centuries until a multilingual stone discovered in Egypt in 1799 provided the key to decoding them.", options: ["Cuneiform", "Hieroglyphics", "Linear B", "Runes"], topic: "History", emoji: "📜", difficulty: "medium" },
    { answer: "Renaissance", description: "This European cultural movement meaning rebirth began in Italy in the 14th century. It was driven by renewed interest in classical Greek and Roman art, science, and philosophy, producing figures like Leonardo da Vinci.", options: ["Enlightenment", "Reformation", "Renaissance", "Romanticism"], topic: "History", emoji: "🎨", difficulty: "medium" },
    { answer: "Morse code", description: "This communication system uses sequences of short and long signals, dots and dashes, to represent letters and numbers. It was invented in the 1830s and remained critical for military communication for over a century.", options: ["Braille", "Binary code", "Semaphore", "Morse code"], topic: "History", emoji: "📡", difficulty: "medium" },
    { answer: "Colosseum", description: "This oval amphitheatre in Rome was completed around 80 AD and could hold up to 80,000 spectators who came to watch gladiatorial contests, animal hunts, and public spectacles.", options: ["Pantheon", "Colosseum", "Forum Romanum", "Circus Maximus"], topic: "History", emoji: "🏟️", difficulty: "easy" },
    { answer: "Silk Road", description: "This ancient network of trade routes connected China, Central Asia, the Middle East, and Europe for over a thousand years. It carried not only silk but also spices, ideas, religions, and diseases between civilisations.", options: ["Amber Road", "Silk Road", "Spice Route", "Tea Horse Road"], topic: "History", emoji: "🐪", difficulty: "medium" },
    // FOOD
    { answer: "Saffron", description: "This spice is the world's most expensive by weight. It consists of dried stigmas hand-picked from a purple flower. It takes roughly 150,000 flowers to produce just one kilogram.", options: ["Turmeric", "Cardamom", "Saffron", "Vanilla"], topic: "Food", emoji: "🌸", difficulty: "hard" },
    { answer: "Fermentation", description: "This biological process uses microorganisms like yeast or bacteria to break down sugars. Without it we would have no bread, wine, beer, yoghurt, cheese, or kimchi.", options: ["Pasteurisation", "Fermentation", "Distillation", "Emulsification"], topic: "Food", emoji: "🍞", difficulty: "medium" },
    { answer: "Truffle", description: "This prized fungus grows underground near tree roots. Because it cannot be cultivated easily, specially trained dogs sniff it out in forests. It is one of the most expensive foods in the world.", options: ["Morel", "Chanterelle", "Truffle", "Porcini"], topic: "Food", emoji: "🍄", difficulty: "hard" },
    { answer: "Umami", description: "This is the fifth basic taste alongside sweet, sour, salty, and bitter. It is a savoury depth of flavour found strongly in aged cheese, tomatoes, mushrooms, and soy sauce.", options: ["Astringent", "Piquant", "Umami", "Bittersweet"], topic: "Food", emoji: "🍖", difficulty: "hard" },
    // TECHNOLOGY
    { answer: "Algorithm", description: "This is a precise step-by-step set of instructions designed to solve a specific problem. Every website recommendation, search result, and social media feed you see is shaped by one.", options: ["Binary", "Protocol", "Algorithm", "Syntax"], topic: "Technology", emoji: "💻", difficulty: "medium" },
    { answer: "Blockchain", description: "This is a distributed digital ledger that stores data in linked cryptographically secured blocks across many computers simultaneously. Once recorded, data is nearly impossible to alter retroactively.", options: ["Database", "Cloud storage", "Blockchain", "Server farm"], topic: "Technology", emoji: "🔗", difficulty: "hard" },
    { answer: "Pixel", description: "This is the smallest addressable element of a digital image. A modern smartphone screen contains millions of them. More of them per inch means a sharper, more detailed image.", options: ["Byte", "Bit", "Pixel", "Vector"], topic: "Technology", emoji: "📱", difficulty: "easy" },
    { answer: "Sonar", description: "This technology detects objects and measures distances by emitting sound pulses and listening for their echoes. Submarines rely on it to navigate underwater, and bats use a biological version to hunt in darkness.", options: ["Radar", "Lidar", "Sonar", "GPS"], topic: "Technology", emoji: "🔊", difficulty: "hard" },
    { answer: "Firewall", description: "This is a network security system that monitors and filters all incoming and outgoing data traffic based on predefined rules, creating a protective barrier between a trusted internal network and the open internet.", options: ["Antivirus", "VPN", "Proxy", "Firewall"], topic: "Technology", emoji: "🔥", difficulty: "medium" },
    // ARTS & MUSIC
    { answer: "Symphony", description: "This is a long complex musical composition written for a full orchestra, typically structured in four contrasting movements. Beethoven's Ninth is considered one of the greatest ever written.", options: ["Concerto", "Sonata", "Symphony", "Overture"], topic: "Music", emoji: "🎻", difficulty: "medium" },
    { answer: "Impressionism", description: "This art movement born in 1860s France used loose brushwork and careful observation of light to capture fleeting moments. Claude Monet's water lily paintings are its most iconic examples.", options: ["Cubism", "Surrealism", "Impressionism", "Expressionism"], topic: "Arts", emoji: "🎨", difficulty: "medium" },
    { answer: "Jazz", description: "This uniquely American musical genre was born in New Orleans at the turn of the 20th century. It is defined by improvisation, swing rhythms, and a blend of African and European musical traditions.", options: ["Blues", "Soul", "Jazz", "Funk"], topic: "Music", emoji: "🎷", difficulty: "easy" },
    { answer: "Calligraphy", description: "This is the ancient art of beautiful decorative handwriting practised across Arabic, Chinese, Japanese, and Western traditions. A skilled practitioner can spend years mastering the pressure and movement of the brush or pen.", options: ["Typography", "Calligraphy", "Graffiti", "Illumination"], topic: "Arts", emoji: "✍️", difficulty: "medium" },
    // HEALTH
    { answer: "Adrenaline", description: "This hormone is released by the adrenal glands when the body senses danger or excitement. It instantly raises heart rate, dilates airways, and redirects blood to the muscles in a survival response.", options: ["Dopamine", "Cortisol", "Adrenaline", "Serotonin"], topic: "Health", emoji: "💉", difficulty: "hard" },
    { answer: "Appendix", description: "This small finger-shaped pouch is attached to the large intestine in the lower right abdomen. Its precise function in adults remains debated, and its removal is one of the most common emergency operations worldwide.", options: ["Gallbladder", "Spleen", "Appendix", "Pancreas"], topic: "Health", emoji: "🫀", difficulty: "hard" },
    { answer: "Placebo", description: "This is a medically inactive substance that can produce real physiological improvements in a patient purely because they believe they are receiving genuine medicine. The effect is widely documented in clinical trials.", options: ["Nocebo", "Placebo", "Analgesic", "Sedative"], topic: "Health", emoji: "💊", difficulty: "hard" },
    // LANGUAGE
    { answer: "Onomatopoeia", description: "This is a word that imitates the actual sound of what it describes. Examples include buzz, crash, sizzle, meow, and bang. Poets and comic book writers use it frequently for dramatic effect.", options: ["Alliteration", "Onomatopoeia", "Metaphor", "Hyperbole"], topic: "Language", emoji: "💬", difficulty: "hard" },
    { answer: "Palindrome", description: "This is a word, phrase, or number that reads identically forwards and backwards. Classic examples include racecar, madam, level, and the phrase: was it a car or a cat I saw.", options: ["Anagram", "Palindrome", "Homophone", "Synonym"], topic: "Language", emoji: "🔁", difficulty: "hard" },
    { answer: "Haiku", description: "This traditional Japanese poetic form has exactly three lines containing 5, 7, and 5 syllables respectively. It traditionally captures a single moment in nature with vivid minimal language.", options: ["Sonnet", "Limerick", "Haiku", "Ode"], topic: "Language", emoji: "📝", difficulty: "medium" },
    { answer: "Dialect", description: "This is a regional variety of a language that differs from the standard form in vocabulary, grammar, or pronunciation. The English spoken in Liverpool, Jamaica, and Texas are all recognisable examples.", options: ["Accent", "Dialect", "Slang", "Jargon"], topic: "Language", emoji: "🗣️", difficulty: "medium" },
    // EXTRA CHALLENGE
    { answer: "Equinox", description: "This astronomical event occurs twice a year when the sun is directly above the equator, making day and night roughly equal in length all over the world. It marks the start of spring and autumn.", options: ["Solstice", "Equinox", "Eclipse", "Perihelion"], topic: "Science", emoji: "🌞", difficulty: "hard" },
    { answer: "Sonar", description: "This technology detects objects and measures distances by emitting sound waves and listening for their echoes. Submarines rely on it to navigate underwater, and bats use a biological version to hunt in complete darkness.", options: ["Radar", "Lidar", "Sonar", "GPS"], topic: "Technology", emoji: "🔊", difficulty: "hard" }
  ];
})();
